id: speedrunner
description: Reach goal asap; accepts risk
weights:
  # Generic/game keys
  progress: 0.0
  coin: 0.0
  death: -0.0
  step_cost: -0.005
  explore_bonus: 0.0
  speed_bonus: 0.05
  success: 1.5
  validation_error: -0.0
  # FormFlow-specific keys
  validation_error_bonus: 0.0       # do not chase errors
  latency_penalty: -0.005           # tolerate small spikes
  page_progress: 0.02               # emphasize forward movement
  page_coverage_bonus: 0.0          # no coverage shaping
  dom_coverage_bonus: 0.0           # no selector coverage
  softlock_penalty: -0.05           # avoid getting stuck
  # Tetris-specific keys
  line_clear_bonus: 0.7
  hole_penalty: -0.005
  height_penalty: -0.005
  topout_penalty: -1.0
  # Blackjack-specific keys
  bust_penalty: -0.8
  win_reward: 1.2
  lose_penalty: -0.8
  draw_bonus: -0.1
  blackjack_bonus: 0.6
